services:
  db:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://db:27017/mydatabase
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://backend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync

volumes:
  mongo-data:
